package nusri.fyp.demo.roboflow.data.response;

import lombok.Data;
import nusri.fyp.demo.roboflow.data.RoboflowResponseData;

import java.util.List;

/**
 * Represents the response for a CLIP embedding request to the Roboflow API.
 * <br> This class contains the data returned by the API after performing a CLIP (Contrastive Language-Image Pretraining) embedding.
 *
 * @author Liu Binghong
 * @since 1.0
 */
@Data
public class ClipEmbeddingResponse implements RoboflowResponseData {

    /**
     * The unique identifier for the CLIP embedding inference request.
     */
    private String inferenceId;

    /**
     * The frame ID of the video or sequence in which the embedding was performed, if applicable.
     */
    private Integer frameId;

    /**
     * The time taken to perform the CLIP embedding, typically in seconds.
     */
    private Float time;

    /**
     * The list of embeddings generated by the CLIP model.
     * <br> Each embedding is represented as a list of floats.
     */
    private List<List<Float>> embeddings;
}
