package nusri.fyp.demo.roboflow.data.response;

import lombok.Data;
import nusri.fyp.demo.roboflow.data.RoboflowResponseData;

import java.util.List;

/**
 * Represents the response for SAM2 (Segmentation and Masking) embedding in the Roboflow API.
 * <br> This class contains the data returned by the API after performing SAM2 embedding on an image.
 * <br> The response includes the image ID, the time taken for the embedding process, and the embeddings generated by the model.
 */
@Data
public class Sam2EmbeddingResponse implements RoboflowResponseData {

    /**
     * The unique identifier for the image on which the SAM2 embedding was performed.
     * <br> This ID can be used to reference or track the specific image.
     */
    private String imageId;

    /**
     * The time taken to perform the SAM2 embedding, typically measured in seconds.
     * <br> This field indicates the duration of the embedding process.
     */
    private double time;

    /**
     * A nested list structure representing the embeddings generated by the SAM2 model.
     * <br> Each layer of the list corresponds to different dimensions or features of the embeddings.
     * <br> The exact structure may depend on the model and the specific embedding process.
     */
    private List<List<List<List<Float>>>> embeddings;
}
