package nusri.fyp.demo.roboflow.data.response;

import lombok.Data;
import nusri.fyp.demo.roboflow.data.RoboflowResponseData;

import java.util.List;

/**
 * Represents the response for SAM (Segmentation and Masking) embedding in the Roboflow API.
 * <br> This class contains the data returned by the API after performing SAM embedding on an image.
 * <br> The response includes the embeddings generated by the model and the time taken for the embedding process.
 */
@Data
public class SamEmbeddingResponse implements RoboflowResponseData {

    /**
     * A nested list structure representing the embeddings generated by the SAM model.
     * <br> Each layer of the list corresponds to different dimensions or features of the embeddings.
     * <br> The exact structure may depend on the model and the specific embedding process.
     * <br> The type can be changed to Double if more precision is required instead of Float.
     */
    private List<List<List<List<Float>>>> embeddings;

    /**
     * The time taken to perform the SAM embedding, typically in seconds.
     * <br> This field indicates the duration of the embedding process.
     */
    private double time;
}
