package nusri.fyp.demo.roboflow.data.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import nusri.fyp.demo.roboflow.data.AnyData;
import nusri.fyp.demo.roboflow.data.RoboflowResponseData;
import nusri.fyp.demo.roboflow.data.entity.workflow.WorkflowOutputData;

import java.util.List;

/**
 * Represents the response for a workflow inference in the Roboflow API.
 * <br> This class contains the outputs from the workflow inference and additional profiler trace data.
 *
 * @author Liu Binghong
 * @since 1.0
 */
@Data
public class WorkflowInferenceResponse implements RoboflowResponseData {

    /**
     * A list of {@link WorkflowOutputData} objects representing the outputs from the workflow inference.
     * <br> Each item in the list corresponds to the results generated by the workflow for a specific input or task.
     */
    private List<WorkflowOutputData> outputs;

    /**
     * A field containing profiler trace data related to the inference.
     * <br> This data, represented as {@link AnyData}, may provide additional performance or execution details about the workflow.
     */
    @JsonProperty("profiler_trace")
    private AnyData profilerTrace;
}
